# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_YVPFhflTG7jIU4FvGjWldjBnk48buKy
"""

import matplotlib.pyplot as plt
#only loading python oriented library
x=[2,3]
x1=[4,3,8]
y1=[2,8,7]
y=[9,5]
plt.xlabel("time")
plt.ylabel("speed")
#plt.plot(x,y,label="water")#this will plot a straight line
#plt.plot(x1,y1,label="sand") #this will draw a straight line
plt.bar(x,y) #this will plot bar
plt.bar(x1,y1) #this will plot bar 
plt.grid(color="green") #to form grid with color in graph
plt.legend() #to show labels with plot
plt.xlim(0,12) # to show min and max in x axis
plt.ylim(0,15) # to show min and max in y axis  
plt.show()

import matplotlib.pyplot as plt
#only loading python oriented library
x=[2,3]
x1=[4,3,8]
y1=[2,8,7]
y=[9,5]
plt.scatter(x,y) #to show only points 
plt.scatter(x1,y1) #to show only points
#plt.bar(x,y) #this will plot bar
#plt.bar(x1,y1)

x=[4,7,8,9,11,5]
y=[13,23,5,7,9,3]
player=["virat",'dhoni','pandya','rohit']
runs=[170,150,100,199]
exp=[0.1,0,0,0]
plt.pie(runs,labels=player,explode=exp,shadow=True,autopct='%1.1f%%')
plt.grid(color='green')
plt.legend()
plt.show()

