# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rftXUjE0v4hFbqZo-FhepEgoKkAWXaxH
"""

import numpy as np 
#creating 1D array
a=np.array([2,7,1,99,4])
type(a)
b=np.array([12,17,11,199,14])
#calling of array
print(a)
print (b)
#calling array with index
print (a[1])
print(b[0])
#adding a and b array
c=a+b
print(c)
#adding 2 to each elements of array
d=a+2
print(d)
#square of each elements of array
s=a**2
print(s)

import numpy as np
#creating 2D array
x=np.array([[2,5,8],[3,6,1]]) #or it is an matrix of 2*3
print(x)
print(x[0][1]) 

#adding 7 to every element
y=x+7
print(y)
#square
y=x**2
print(y)
z=np.array([[2,7],[3,8],[2,9],[9,4]])
print(z)
x.shape # to get matrix ex -2*3 
z.shape

print(z[0:2]) # to print specific row

print(z[0:,0]) #to print coloum only

print(z[0:2,0])

print(x[0:2,0:2])

print(x[0: ,[0,2]])

print(x[[0,2]])

print(x[[0,3],1])

x1=x.reshape(3,2) #to reshape the 2*3 into 3*2

np.zeros((3,6)) #to get zeros as all element
np.ones((5,2)) # to get ones as all element
np.full((4,5),9) # it will fill the matrix with 9

import numpy as np
b=np.array([1,9,7])
